-- MySQL Script generated by MySQL Workbench
-- dom 28 abr 2024 11:53:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`classificacao_indicativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`classificacao_indicativa` (
  `idclassificacao_indicativa` INT NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `cor` VARCHAR(10) NOT NULL,
  `idade_minima` INT NOT NULL,
  PRIMARY KEY (`idclassificacao_indicativa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pais` (
  `idpais` INT NOT NULL,
  `nome` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idpais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produtora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produtora` (
  `idprodutora` INT NOT NULL,
  `nome` VARCHAR(20) NOT NULL,
  `pais_sede_idpais` INT NOT NULL,
  PRIMARY KEY (`idprodutora`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_produtora_pais1_idx` (`pais_sede_idpais` ASC) VISIBLE,
  CONSTRAINT `fk_produtora_pais1`
    FOREIGN KEY (`pais_sede_idpais`)
    REFERENCES `mydb`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`diretor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`diretor` (
  `iddiretor` INT NOT NULL,
  `nome` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`iddiretor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roteirista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roteirista` (
  `idroteirista` INT NOT NULL,
  `nome` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idroteirista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`filme` (
  `idfilme` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `duracao` INT NOT NULL,
  `ano_lancamento` INT(4) NOT NULL,
  `descricao` TEXT NOT NULL,
  `classificacao_indicativa_idclassificacao_indicativa` INT NOT NULL,
  `produtora_idprodutora` INT NOT NULL,
  `diretor_principal_iddiretor` INT NOT NULL,
  `roteirista_principal_idroteirista` INT NOT NULL,
  PRIMARY KEY (`idfilme`),
  INDEX `fk_filmes_classificacao_indicativa1_idx` (`classificacao_indicativa_idclassificacao_indicativa` ASC) VISIBLE,
  INDEX `fk_filmes_produtora1_idx` (`produtora_idprodutora` ASC) VISIBLE,
  INDEX `fk_filmes_diretor1_idx` (`diretor_principal_iddiretor` ASC) VISIBLE,
  INDEX `fk_filmes_roteiristas1_idx` (`roteirista_principal_idroteirista` ASC) VISIBLE,
  CONSTRAINT `fk_filmes_classificacao_indicativa1`
    FOREIGN KEY (`classificacao_indicativa_idclassificacao_indicativa`)
    REFERENCES `mydb`.`classificacao_indicativa` (`idclassificacao_indicativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filmes_produtora1`
    FOREIGN KEY (`produtora_idprodutora`)
    REFERENCES `mydb`.`produtora` (`idprodutora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filmes_diretor1`
    FOREIGN KEY (`diretor_principal_iddiretor`)
    REFERENCES `mydb`.`diretor` (`iddiretor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filmes_roteiristas1`
    FOREIGN KEY (`roteirista_principal_idroteirista`)
    REFERENCES `mydb`.`roteirista` (`idroteirista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ator` (
  `idator` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idator`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria_do_premio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria_do_premio` (
  `idcategoria_do_premio` INT NOT NULL,
  `nome_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria_do_premio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`elenco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`elenco` (
  `filme_idfilme` INT NOT NULL,
  `ator_idator` INT NOT NULL,
  PRIMARY KEY (`filme_idfilme`, `ator_idator`),
  INDEX `fk_filmes_has_atores_atores1_idx` (`ator_idator` ASC) VISIBLE,
  INDEX `fk_filmes_has_atores_filmes1_idx` (`filme_idfilme` ASC) VISIBLE,
  CONSTRAINT `fk_filmes_has_atores_filmes1`
    FOREIGN KEY (`filme_idfilme`)
    REFERENCES `mydb`.`filme` (`idfilme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filmes_has_atores_atores1`
    FOREIGN KEY (`ator_idator`)
    REFERENCES `mydb`.`ator` (`idator`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`premio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`premio` (
  `idpremio` INT NOT NULL,
  `nome` VARCHAR(20) NOT NULL,
  `ano` INT(4) NOT NULL,
  `categoria_idcategoria_do_premio` INT NOT NULL,
  `elenco_filme_idfilme` INT NULL,
  `elenco_ator_idator` INT NULL,
  `ator_idator` INT NULL,
  `diretor_iddiretor` INT NULL,
  `roteirista_idroteirista` INT NULL,
  `produtora_idprodutora` INT NULL,
  `filme_idfilme` INT NOT NULL,
  PRIMARY KEY (`idpremio`),
  INDEX `fk_premios_categoria_do_premio1_idx` (`categoria_idcategoria_do_premio` ASC) VISIBLE,
  INDEX `fk_premios_Elenco1_idx` (`elenco_filme_idfilme` ASC, `elenco_ator_idator` ASC) VISIBLE,
  INDEX `fk_premios_atores1_idx` (`ator_idator` ASC) VISIBLE,
  INDEX `fk_premios_diretores1_idx` (`diretor_iddiretor` ASC) VISIBLE,
  INDEX `fk_premios_roteiristas1_idx` (`roteirista_idroteirista` ASC) VISIBLE,
  INDEX `fk_premios_produtora1_idx` (`produtora_idprodutora` ASC) VISIBLE,
  INDEX `fk_premios_filmes1_idx` (`filme_idfilme` ASC) VISIBLE,
  CONSTRAINT `fk_premios_categoria_do_premio1`
    FOREIGN KEY (`categoria_idcategoria_do_premio`)
    REFERENCES `mydb`.`categoria_do_premio` (`idcategoria_do_premio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_premios_Elenco1`
    FOREIGN KEY (`elenco_filme_idfilme` , `elenco_ator_idator`)
    REFERENCES `mydb`.`elenco` (`filme_idfilme` , `ator_idator`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_premios_atores1`
    FOREIGN KEY (`ator_idator`)
    REFERENCES `mydb`.`ator` (`idator`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_premios_diretores1`
    FOREIGN KEY (`diretor_iddiretor`)
    REFERENCES `mydb`.`diretor` (`iddiretor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_premios_roteiristas1`
    FOREIGN KEY (`roteirista_idroteirista`)
    REFERENCES `mydb`.`roteirista` (`idroteirista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_premios_produtora1`
    FOREIGN KEY (`produtora_idprodutora`)
    REFERENCES `mydb`.`produtora` (`idprodutora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_premios_filmes1`
    FOREIGN KEY (`filme_idfilme`)
    REFERENCES `mydb`.`filme` (`idfilme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genero` (
  `idgenero` INT NOT NULL,
  `nome` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idgenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`espectador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`espectador` (
  `idespectador` INT NOT NULL,
  `nome` VARCHAR(25) NOT NULL,
  `idade` INT NOT NULL,
  `n_filmes_assistidos` INT NOT NULL,
  `pais_idpais` INT NOT NULL,
  PRIMARY KEY (`idespectador`),
  INDEX `fk_espectador_pais1_idx` (`pais_idpais` ASC) VISIBLE,
  CONSTRAINT `fk_espectador_pais1`
    FOREIGN KEY (`pais_idpais`)
    REFERENCES `mydb`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avaliacao` (
  `idavaliacao` INT NOT NULL,
  `nota` INT NOT NULL,
  `comentario` TEXT NULL,
  `espectador_idespectador` INT NOT NULL,
  `filme_idfilme` INT NOT NULL,
  PRIMARY KEY (`idavaliacao`),
  INDEX `fk_avaliacao_clientes1_idx` (`espectador_idespectador` ASC) VISIBLE,
  INDEX `fk_avaliacao_filmes1_idx` (`filme_idfilme` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_clientes1`
    FOREIGN KEY (`espectador_idespectador`)
    REFERENCES `mydb`.`espectador` (`idespectador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_filmes1`
    FOREIGN KEY (`filme_idfilme`)
    REFERENCES `mydb`.`filme` (`idfilme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`idioma` (
  `ididioma` INT NOT NULL,
  `nome_idioma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ididioma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`filme_has_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`filme_has_genero` (
  `filme_idfilmes` INT NOT NULL,
  `genero_idgenero` INT NOT NULL,
  PRIMARY KEY (`filme_idfilmes`, `genero_idgenero`),
  INDEX `fk_filmes_has_generos_generos1_idx` (`genero_idgenero` ASC) VISIBLE,
  INDEX `fk_filmes_has_generos_filmes1_idx` (`filme_idfilmes` ASC) VISIBLE,
  CONSTRAINT `fk_filmes_has_generos_filmes1`
    FOREIGN KEY (`filme_idfilmes`)
    REFERENCES `mydb`.`filme` (`idfilme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filmes_has_generos_generos1`
    FOREIGN KEY (`genero_idgenero`)
    REFERENCES `mydb`.`genero` (`idgenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dublagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dublagem` (
  `idioma_ididioma` INT NOT NULL,
  `filme_idfilme` INT NOT NULL,
  PRIMARY KEY (`idioma_ididioma`, `filme_idfilme`),
  INDEX `fk_idiomas_has_filmes_filmes1_idx` (`filme_idfilme` ASC) VISIBLE,
  INDEX `fk_idiomas_has_filmes_idiomas1_idx` (`idioma_ididioma` ASC) VISIBLE,
  CONSTRAINT `fk_idiomas_has_filmes_idiomas1`
    FOREIGN KEY (`idioma_ididioma`)
    REFERENCES `mydb`.`idioma` (`ididioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idiomas_has_filmes_filmes1`
    FOREIGN KEY (`filme_idfilme`)
    REFERENCES `mydb`.`filme` (`idfilme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`legenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`legenda` (
  `idioma_ididioma` INT NOT NULL,
  `filme_idfilme` INT NOT NULL,
  PRIMARY KEY (`idioma_ididioma`, `filme_idfilme`),
  INDEX `fk_idiomas_has_filmes_filmes2_idx` (`filme_idfilme` ASC) VISIBLE,
  INDEX `fk_idiomas_has_filmes_idiomas2_idx` (`idioma_ididioma` ASC) VISIBLE,
  CONSTRAINT `fk_idiomas_has_filmes_idiomas2`
    FOREIGN KEY (`idioma_ididioma`)
    REFERENCES `mydb`.`idioma` (`ididioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idiomas_has_filmes_filmes2`
    FOREIGN KEY (`filme_idfilme`)
    REFERENCES `mydb`.`filme` (`idfilme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
